<div class="title">HISTORIA</div>
<div>
  <p>Corría el año 1979 cuando el Club de Leones, una entidad de servicio de Comodoro Rivadavia con reconocimiento internacional, hizo suya la preocupación por la falta de atención en cuanto a enfermedades oncológicas que existía en la ciudad. A raíz de esta situación puso en marcha una campaña pública para recaudar fondos para la adquisición de una Bomba de Cobalto que se instalaría en el Hospital Regional de la ciudad. Dicho equipo sería utilizado para realizar los tratamientos mediante Radioterapia.</p>
	<p>La comunidad de la ciudad y las de la región, tales como: Rada Tilly, Sarmiento, Esquel, Puerto Madryn, Caleta Olivia, Las Heras, Pico Truncado y Puerto Deseado, realizaron recaudaciones que superaron los valores del equipamiento mencionado, por lo que se pudo donar además de una Bomba de Cobalto TERATRÓN 780, una Cámara Gamma PICKER, equipo este último que se utiliza para el diagnostico y genéricamente se lo denomina: Medicina Nuclear.</p>
  <div id="full-history" class="center blue-text">Seguir leyendo...</div>
<div>
<div id="history-hidden">
	<p>Paralelamente la Provincia del Chubut, a través de su Área de Salud Pública realizaba las obras civiles necesarias para su instalación y puesta en funcionamiento. Estas obras constaban de un Bunker de hormigón armado y dependencias anexas, consultorios, etc. A su vez debía comenzar la incorporación y formación de recursos humanos para la atención de los nuevos servicios.</p>
	<p>El 13 de Diciembre de 1984 el Sr. Presidente de la Nación, Dr. Ricardo ALFONSIN junto con Autoridades Provinciales y Municipales inauguraron formalmente el Centro de Aplicaciones Bionucleares, llamado en adelante CABIN.</p>
	<p>Distintas circunstancias convergieron para impedir la puesta en marcha de los servicios de salud de alta complejidad para los cuales la comunidad había aportado solidariamente.</p>
	<p>Ante tal realidad, el Club de Leones comenzó a madurar la idea de buscar otras alternativas que no trabaran la puesta en funcionamiento de los equipos de tratamiento y diagnóstico con los que ya contaban y que pudieran atender pacientes de todo tipo, con cobertura social o sin ella.</p>
	<p>Así, como resultado de las múltiples reuniones con distintos protagonistas, surge el 18 de Octubre de 1988, con ese propósito la constitución del CONSORCIO DE ADMINISTRACIÓN DEL CENTRO DE APLICACIONES BIONUCLEARES (C.A.B.I.N.) impulsado por el entonces Ministro de Salud, Dr. José Manuel Corchuelo Blasco e integrado por 16 representantes de diferentes entidades de la región, a razón de dos personas por cada una, para representar a: Gobierno de la Provincia del Chubut, Municipalidades de Comodoro Rivadavia y Rada Tilly, Asociación Española de Socorros Mutuos, Sociedad Cooperativa Popular Ltda., Club de Leones de Comodoro Rivadavia, Asociación de Obras Sociales (A.D.O.S.) y Petroquímica Comodoro Rivadavia. Posteriormente se incorporó la Universidad Nacional de la Patagonia “SAN JUAN BOSCO”. El convenio es ratificado por LEY provincial  Nº 3262 y Decreto Nº 47.
	Cabe resaltar que todos los integrantes del Consorcio de Administración, desarrollan sus tareas “Ad honorem”, es decir sin recibir ningún tipo de compensación monetaria ni material.</p>
	<p>A comienzos de 1989 se contrató al Dr. Miguel A. Keropian, médico Especialista en Cobaltoterapia, a fin de dar inicio en el mes de Junio, a las primeras prestaciones con la BOMBA DE COBALTO.</p>
	<p>En Julio de 1990 comienza a funcionar el servicio de Medicina Nuclear con la puesta en funcionamiento de la Cámara Gamma planar.</p>
	<p>Estos fueron los dos puntos de inflexión, a partir de los cuales el C.A.B.I.N. comenzó a incorporar nuevas técnicas, tratamientos, equipamiento y recursos humanos.</p>
	<p>En Junio de 1992 se inició el servicio de Braquiterapia. En Mayo de 1993 se reabrió el laboratorio de Radio Inmuno Ensayo. En Julio de 1995 se implementó la Betaterapia.</p>
	<p>Dado el crecimiento de la Institución se decide comenzar con la formación de recursos humanos a través de una residencia médica en Radioterapia.</p>
  <p>En Octubre del mismo año, se inaugura el servicio de Psicoterapia a pacientes individuales y al grupo de autoayuda.</p>
	<p>Los avances tecnológicos acompañan las optimizaciones en cuanto a tratamientos, para lo cual el C.A.B.I.N. siempre trató de actualizarse, y es así que en Octubre de 1998 se pone en funcionamiento el primer Simulador Radiológico y en Septiembre de 1999 la Cámara Gamma Tomográfica SPECT, que reemplazó a la Cámara Planar. Todo el equipamiento descripto se adquirió con recursos económicos propios.</p>
	<p>Durante la ya consolidada democracia, el Gobierno Nacional, adquiere equipamientos varios y por mediación del Poder Ejecutivo de la Provincia de Chubut y de sus legisladores, se obtiene la donación al C.A.B.I.N. de un Simulador Radiológico y del Acelerador Lineal, ambos de última generación.</p>
  <p>Entre Noviembre de 2001 y Abril de 2002 se remodela la planta física poniéndose en funcionamiento el nuevo Simulador Radiológico SIEMENS modelo SimView NT como paso previo a la instalación del Acelerador Lineal, para el cual debía realizarse una obra de gran envergadura, ya que requería de un nuevo BUNKER, con características acordes a las nuevas energías que comenzarían a utilizarse.</p>
	<p>En Junio de 2003 se finalizan las obras de dicho bunker, con la colaboración de la comunidad de COMODORO RIVADAVIA, personas y empresas que donaron todos los materiales y mano de obra. Cabe destacar a Petroquímica que siendo consorcista donó 240 toneladas de cemento a granel que las distintas empresas de construcción de la ciudad traían y elaboraban a su costo para la obra. Contamos con la supervisión de profesionales de la UNIV. NAC. de la PATAGONIA “SAN JUAN BOSCO”, a través de la FACULTAD DE INGENIERIA. El costo estimado en ese momento fue de $ 1.800.000,00. A raíz de la incorporación del acelerador Lineal se requiere por ordenanza de la Comisión Nacional de Energía Atómica la incorporación de un servicio permanente de Física aplicada a las radiaciones en medicina, por lo cual se inaugura el Departamento de Física de las Radiaciones con la incorporación de dos Físicos Especialistas.</p>
	<p>A comienzos del año 2004 se inicia la instalación del nuevo Acelerador Lineal de SIEMENS modelo Mevatron Primus MD2. Simultáneamente comienza la formación de recursos humanos en física de las radiaciones y mantenimiento y reparación de equipos con la incorporación de un Bioingeniero y una Ingeniera Electrónica. Con el incremento del trabajo se incorpora un segundo Bioingeniero que finaliza a fines de 2016 su especialización en física aplicada a medicina en el Instituto Balseiro de Bariloche.</p>
	<p>El C.A.B.I.N. siempre ha tratado de formar parte de diferentes grupos de investigación de manera de estar en constante avance en cuanto a tecnologías y técnicas. Como resultado de dicha trayectoria, fue convocado por la IAEA (Internacional Atomic Energy Agency) para formar parte de un trabajo de investigación internacional junto con otros seis países, participando del Proyecto de Investigación sobre Aseguramiento de la Calidad de Planificadores de Radioterapia. Para dicho emprendimiento fueron invitados sólo siete Centros de Atención de: Alemania, Argentina, Estados Unidos, Sudáfrica, Cuba, Estonia y Tailandia, a razón de uno por país y tiene como objetivo contribuir al establecimiento de protocolos que sean cumplidos tanto por los proveedores, como por los que prestan el Servicio de Radioterapia.</p>
	<p>Finalmente en Agosto de 2004 se inician los tratamientos con el nuevo Acelerador Lineal, inaugurándose oficialmente en Octubre de 2004.</p>
	<p>En diciembre/2004, el Gobierno de la Provincia de Chubut, concretó la donación de U$S 80.000 para la compra de un segundo Acelerador Lineal, Marca SIEMMENS, Modelo MEVATRON 67, reacondicionado a nuevo, que reemplazó a la Bomba de Cobalto original.</p>
  <p>Luego de la implementación del nuevo equipamiento, de los recursos humanos, y las nuevas técnicas en terapia radiante, comenzó a surgir la necesidad de crear el Servicio de Oncología. Se incorporó al cuerpo médico, a partir de marzo/2005, una médica especialista en oncología clínica. Esto hizo necesaria la construcción de un Hospital de Día dónde los pacientes pudieran realizarse las aplicaciones de Quimioterapia Ambulatoria, en un clima cálido y sereno, dándose comienzo a una nueva remodelación del Centro para que a partir de setiembre de 2005 se inaugure dicha dependencia, con el inicio de las prestaciones. Actualmente el servicio de Oncología cuenta con una oncóloga, una hemato-oncóloga y dos clínicas.</p>
  <p>En febrero de 2008, se concretó la compra y entrega de un PHANTOM BLUE y un STAR TRACK, ambos importados de Alemania. Son elementos que se utilizan para control de calidad de los Aceleradores Lineales, ya que permiten la supervisión diaria de la dosimetría y calibración del haz de las radiaciones, lo que asegura la precisión requerida en los procesos de terapia radiante.</p>
  <p>El avance tecnológico, las nuevas opciones terapéuticas y el entrenamiento en ellas nos permitió incorporar a los tratamientos con radioterapia, el sistema IMRT (Intensidad Modulada de Radio Terapia) y la radioterapia 3 D que posibilita aumentar la dosis planificada y con ello lograr un mayor control de la enfermedad.</p>
  <p>Hemos realizado en la primera mitad del 2011 el primer procedimiento en la Patagonia de Cirugía Estereotáxica, que consiste en tratar tumores encefálicos sin operar. El procedimiento consiste en colocar un marco esteroatáxico en la cabeza del paciente, realizar estudios de imágenes y planificar la administración de una alta dosis de radiación en un punto del cerebro en una sola sesión, evitando la morbilidad neurológica de una neurocirugía. Resumiendo, transforma un procedimiento de alta complejidad, en un tratamiento ambulatorio.</p>
  <p>A fines del año 2006, la Autoridad Regulatoria Nuclear, dispuso inhabilitar la sala en la Clínica del Valle donde funcionaba la Braquiterapia por las reformas introducidas en dicho edificio. Se recurrió nuevamente a Provincia y con su aporte monetario y la contribución de la comunidad, en Julio/08 hemos habilitado nuevamente el Servicio en C.A.B.I.N., con la construcción de un BUNKER ad hoc donde la paciente permanece internada por 3 días para realizar el tratamiento. Destacamos que no existe otro lugar en la Patagonia para el tratamiento con radiación local del cáncer de cuello de útero (uno de los más frecuentes en la mujer).</p>
  <p>En función de la ley provincial de creación del CABIN  y el  convenio oportunamente firmado entre el Consorcio de Administración  y el Gobierno de la Provincia del Chubut, se atiende sin cargo en todos los Servicios a los indigentes que provengan de los Servicios Sociales de los Hospitales Provinciales o de los Municipios.
  Dichas prestaciones alcanzan en promedio al 16 % del total de los servicios brindados. Con lo facturado a obras sociales y prepagas se mantiene en funcionamiento el centro. CABIN no recibe aportes estatales o privados  periódicos y sistemáticos para el pago de sueldos, honorarios, mantenimiento de equipos, etc.</p>
  <p>En octubre del 2010 recibimos la donación de Pan American Energy de $364.108,55 para la compra de una Cámara Gamma Tomográfica de doble cabezal marca ADAD, modelo VERTEX PLUS, para reemplazar la anterior.</p>
  <p>En setiembre de 2011 el Consorcio de Administración del CABIN, aprobó la creación del Comité de Evaluación y Seguimiento de Investigaciones (C.E.S.I.) con el objeto de, monitorear y controlar toda Investigación Biomédica que se desarrolle en el C.A.B.I.N, protegiendo los derechos de los pacientes involucrados.</p>
  <p>En febrero 2015 se relanza el funcionamiento del servicio de asistencia psicológica para pacientes oncológicos. Se mantiene en funcionamiento el grupo de autoayuda de pacientes oncológicos actuales, en remisión o familiares denominado “Sentimientos “, que se reúnen en las instalaciones de CABIN.</p>
  <p>En la actualidad se están realizando los trabajos de construcción de ampliación de CABIN, en una superficie de 790 m2. En dicha planta alta se trasladará: Hospital de Día (Quimioterapia Ambulatoria) con consultorio para médico oncólogo, Laboratorio de Análisis Clínicos, Administración, Dirección Médica y Administrativa, Vestuarios y Comedor para el personal, Salón Auditorio para 50 personas, Departamento de Investigaciones Científicas, consultorios y dependencias sanitarias.</p>
  <p>El avance de obra es del 48%, estimándose la habilitación a fines del segundo semestre del 2016. Durante el 2016 en Medicina Nuclear se incorporó un médico especialista en Cardiología Nuclear al equipo de profesionales ya existentes.</p>
  <p>También durante este año se incluyó a CABIN en un ambicioso proyecto denominado “Plan Nacional Nuclear“. Este plan llevado adelante por la Comisión Nacional de Energía Atómica y ejecutado por INVAP consiste en la construcción de una planta física de 1600 m2 con la incorporación de: 2 (dos) nuevos Aceleradores, Braquiterapia de Alta Tasa, Tomógrafo Computado, un Pet / CT, Spect CT y un Ciclotrón (equipo que produce radioisótopos para utilizar en el Pet / CT). Se estima que estaría funcionando para fines del 2018.</p>
  <p>Resumiendo todo lo expuesto, podemos afirmar que C.A.B.I.N. hoy es una realidad que lo ha convertido en el Centro Regional de Referencia para el tratamiento de las enfermedades oncológicas, tanto en lo tecnológico, como en la capacidad profesional de sus integrantes y en la constante actualización de los medios con que cuenta.</p>
  <p>Asimismo destacamos que el modelo de gestión ha demostrado su alta calidad en las prestaciones que brinda a la comunidad y que podría trasladarse la experiencia a otras actividades donde el Estado es prestador de servicios.</p>
<div>
